# Generated by Django 4.0.5 on 2022-06-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='country')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('experiment', models.FileField(blank=True, null=True, upload_to='experiments/%Y/%m/%d')),
                ('experiment_status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
                'get_latest_by': 'created_time',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=100, verbose_name='months')),
            ],
            options={
                'verbose_name_plural': 'Months',
                'db_table': 'month',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('note', models.FileField(blank=True, null=True, upload_to='notes/%Y/%m/%d')),
                ('note_status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
                'get_latest_by': 'created_time',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PHenology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('pheno_status', models.BooleanField(default=False)),
                ('eggs', models.TextField(null=True)),
                ('day_eggs', models.TextField(blank=True, max_length=100, null=True)),
                ('larva', models.TextField(blank=True, null=True)),
                ('day_larva', models.TextField(blank=True, max_length=100, null=True)),
                ('fungus', models.TextField(blank=True, null=True)),
                ('day_fungus', models.TextField(blank=True, max_length=100, null=True)),
                ('mature', models.TextField(blank=True, null=True)),
                ('day_mature', models.TextField(blank=True, max_length=100, null=True)),
                ('manipulation', models.TextField(blank=True, null=True)),
                ('day_m', models.TextField(blank=True, max_length=100, null=True)),
                ('prediction', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Phenology detail',
                'verbose_name_plural': 'Phenology details',
                'db_table': 'PHenology',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d')),
                ('photo_status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
                'get_latest_by': 'created_time',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('type', models.CharField(default='', max_length=300)),
                ('add_data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('product_status', models.BooleanField(default=False)),
                ('product', models.CharField(blank=True, max_length=35, null=True)),
                ('product_hs_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='KOD TN ved')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Production',
            },
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='product type')),
            ],
            options={
                'verbose_name_plural': 'Product Types',
                'db_table': 'product type',
            },
        ),
        migrations.CreateModel(
            name='Protect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('protect_status', models.BooleanField(default=False)),
                ('agro_protect', models.CharField(blank=True, max_length=255, null=True)),
                ('bio_protect', models.CharField(blank=True, max_length=255, null=True)),
                ('chemistry_protect', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Protection result',
                'verbose_name_plural': 'Protection results',
                'db_table': 'protect',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('quarantine_type', models.CharField(blank=True, choices=[('1', 'Yes'), ('2', 'No')], max_length=10)),
                ('name_latin', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Латинское названи')),
                ('name_uzb', models.CharField(blank=True, max_length=25, null=True)),
                ('type', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('country', models.ManyToManyField(blank=True, to='research.countries', verbose_name='Countries+')),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Research',
                'default_permissions': (),
            },
        ),
    ]
