# Generated by Django 4.0.5 on 2022-06-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alldata',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='alldata',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='production',
            name='product',
        ),
        migrations.AddField(
            model_name='production',
            name='product',
            field=models.ManyToManyField(blank=True, to='research.plants', verbose_name='Plants+'),
        ),
    ]
