# Generated by Django 4.0.5 on 2022-06-09 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_experiment_confirmation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenology',
            name='phenology',
        ),
        migrations.RemoveField(
            model_name='production',
            name='production',
        ),
        migrations.RemoveField(
            model_name='protect',
            name='protection',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiments', related_query_name='experiments', to='research.alldata'),
        ),
        migrations.AlterField(
            model_name='note',
            name='notes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', related_query_name='notes', to='research.alldata'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', related_query_name='photos', to='research.alldata'),
        ),
    ]
