# Generated by Django 4.0.5 on 2022-06-13 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_remove_alldata_all_experiment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='notes',
            new_name='noteo',
        ),
        migrations.AlterField(
            model_name='photo',
            name='all_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photes', to='research.alldata'),
        ),
    ]
